Fix PermissionError exception when clamping mtime
In case the user has no permission to change the modification time of
the output directory, bdebstrap will fail:

```
Traceback (most recent call last):
  File "bdebstrap", line 795, in <module>
    sys.exit(main(sys.argv[1:]))
  File "bdebstrap", line 778, in main
    Mmdebstrap(config).call(args.output, args.simulate)
  File "bdebstrap", line 143, in call
    clamp_mtime(path, self.config.source_date_epoch)
  File "bdebstrap", line 152, in clamp_mtime
    os.utime(path, (int(source_date_epoch), int(source_date_epoch)))
PermissionError: [Errno 1] Operation not permitted
```

Instead of failing with an exception, print an error message and
continue.

Signed-off-by: Benjamin Drung <bdrung@posteo.de>