setup.py: Fix building with setuptools 65.5.0
Building with setuptools 65.5.0 fails:

```
setup.py:19: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.cmd
/usr/lib/python3/dist-packages/_distutils_hack/__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
/usr/lib/python3/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "setup.py", line 74, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 172, in setup
    ok = dist.parse_command_line()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 474, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1107, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 540, in _parse_command_opts
    raise DistutilsClassError(
distutils.errors.DistutilsClassError: command class <class '__main__.BuildCommand'> must subclass Command
Error: Process completed with exit code 1.
```

`distutils` is deprecated and should be replace. See [PEP
632](https://peps.python.org/pep-0632/) and
https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html.

setuptools as of version 65.5 does not support overwriting the
`build_scripts` or `clean` command. Overwriting the `build_py` command
is not an option since bdebstrap only ships a script and no Python
module.

Therefore keep using the `distutils` module, but import it after
setuptools has modified it.

Bug-Debian: https://bugs.debian.org/1022513
Signed-off-by: Benjamin Drung <bdrung@posteo.de>